name: ccruntime e2e tests
on:
  workflow_call:

permissions:
  contents: read

jobs:
  e2e:
    name: operator tests
    strategy:
      matrix:
        runtimeclass:
          - "kata-qemu"
          - "kata-clh"
        instance:
          - "az-ubuntu-2004"
          - "az-ubuntu-2204"
          - "s390x"
        exclude:
          - runtimeclass: "kata-clh"
            instance: "s390x"
    runs-on: ${{ matrix.instance }}
    steps:
      - name: Take a pre-action for self-hosted runner
        run: |
          if [ -f ${HOME}/script/pre_action.sh ]; then
            ${HOME}/script/pre_action.sh cc-operator
          fi

      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ansible python-is-python3

      - name: Run e2e tests
        run: |
          cd tests/e2e
          export PATH="$PATH:/usr/local/bin"
          args="-u"
          if [ $RUNNING_INSTANCE = "s390x" ]; then
            args=""
          fi
          ./run-local.sh -r "${{ matrix.runtimeclass }}" "${args}"
        env:
          RUNNING_INSTANCE: ${{ matrix.instance }}

      - name: Take a post-action
        if: always()
        run: |
          if [ -f ${HOME}/script/post_action.sh ]; then
            ${HOME}/script/post_action.sh cc-operator
          fi
