name: ccruntime e2e test for PR
on:
  push:
    branches:
      - 'hchoi-install-debug'
  #pull_request_target:
  #  branches:
  #    - 'main'
  #  types:
  #    - opened
  #    - synchronize
  #    - reopened
  #    - labeled

jobs:
  e2e-pr:
    uses: ./.github/workflows/ccruntime_e2e.yaml
    with:
      target-branch: main
      commit-hash: ${{ github.sha }}
