name: Operator E2E Test Nightly for s390x
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  operator-e2e-nightly:
    uses: ./.github/workflows/ci-s390x.yaml

  check-internal-test-result:
    runs-on: s390x
    strategy:
      fail-fast: false
      matrix:
        test_title:
          - cc-operator-e2e-tests
    steps:
    - name: Fetch a test result for {{ matrix.test_title }}
      run: |
        file_name="${TEST_TITLE}-$(date +%Y-%m-%d).log"
        /home/${USER}/script/handle_test_log.sh download $file_name
      env:
        TEST_TITLE: ${{ matrix.test_title }}
